//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace PalletReceive.DMServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDMCheckService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProxyBase))]
    public partial class DMCheckService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DMCheckService() {
            this.Url = "http://172.17.0.50/ServicesD365/DMCheckService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetPing() {
            object[] results = this.Invoke("GetPing", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPing", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPalletInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DMExportContract GetPalletInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum) {
            object[] results = this.Invoke("GetPalletInfo", new object[] {
                        palletNum});
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPalletInfo(string palletNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPalletInfo", new object[] {
                        palletNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract EndGetPalletInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPalletInfoByRecordId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DMExportContract GetPalletInfoByRecordId(long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified) {
            object[] results = this.Invoke("GetPalletInfoByRecordId", new object[] {
                        recordId,
                        recordIdSpecified});
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPalletInfoByRecordId(long recordId, bool recordIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPalletInfoByRecordId", new object[] {
                        recordId,
                        recordIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract EndGetPalletInfoByRecordId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ConfirmPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConfirmPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, bool isFromSL, [System.Xml.Serialization.XmlIgnoreAttribute()] bool isFromSLSpecified, out bool ConfirmPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ConfirmPalletReceiveResultSpecified) {
            object[] results = this.Invoke("ConfirmPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified});
            ConfirmPalletReceiveResult = ((bool)(results[0]));
            ConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConfirmPalletReceive(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, bool isFromSL, bool isFromSLSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConfirmPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndConfirmPalletReceive(System.IAsyncResult asyncResult, out bool ConfirmPalletReceiveResult, out bool ConfirmPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ConfirmPalletReceiveResult = ((bool)(results[0]));
            ConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ConfirmPalletAndLocationReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmPalletAndLocationReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationId, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, bool isFromSL, [System.Xml.Serialization.XmlIgnoreAttribute()] bool isFromSLSpecified) {
            object[] results = this.Invoke("ConfirmPalletAndLocationReceive", new object[] {
                        palletNum,
                        locationId,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConfirmPalletAndLocationReceive(string palletNum, string locationId, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, bool isFromSL, bool isFromSLSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConfirmPalletAndLocationReceive", new object[] {
                        palletNum,
                        locationId,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndConfirmPalletAndLocationReceive(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/CancelPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, out bool CancelPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CancelPalletReceiveResultSpecified) {
            object[] results = this.Invoke("CancelPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser});
            CancelPalletReceiveResult = ((bool)(results[0]));
            CancelPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelPalletReceive(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCancelPalletReceive(System.IAsyncResult asyncResult, out bool CancelPalletReceiveResult, out bool CancelPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CancelPalletReceiveResult = ((bool)(results[0]));
            CancelPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/UpdateAndConfirmPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAndConfirmPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DMExportContract pallet, out bool UpdateAndConfirmPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateAndConfirmPalletReceiveResultSpecified) {
            object[] results = this.Invoke("UpdateAndConfirmPalletReceive", new object[] {
                        pallet});
            UpdateAndConfirmPalletReceiveResult = ((bool)(results[0]));
            UpdateAndConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateAndConfirmPalletReceive(DMExportContract pallet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateAndConfirmPalletReceive", new object[] {
                        pallet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateAndConfirmPalletReceive(System.IAsyncResult asyncResult, out bool UpdateAndConfirmPalletReceiveResult, out bool UpdateAndConfirmPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            UpdateAndConfirmPalletReceiveResult = ((bool)(results[0]));
            UpdateAndConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/PrintAgainPallet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintAgainPallet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, out bool PrintAgainPalletResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool PrintAgainPalletResultSpecified) {
            object[] results = this.Invoke("PrintAgainPallet", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser});
            PrintAgainPalletResult = ((bool)(results[0]));
            PrintAgainPalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintAgainPallet(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintAgainPallet", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrintAgainPallet(System.IAsyncResult asyncResult, out bool PrintAgainPalletResult, out bool PrintAgainPalletResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            PrintAgainPalletResult = ((bool)(results[0]));
            PrintAgainPalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/DMClearPrintAgain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
        public DMExportMiniContract[] DMClearPrintAgain() {
            object[] results = this.Invoke("DMClearPrintAgain", new object[0]);
            return ((DMExportMiniContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDMClearPrintAgain(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DMClearPrintAgain", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportMiniContract[] EndDMClearPrintAgain(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportMiniContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/UpdateOfflinePallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
        public DMExportContract[] UpdateOfflinePallets([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")] DMExportOfflineContract[] lines) {
            object[] results = this.Invoke("UpdateOfflinePallets", new object[] {
                        lines});
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateOfflinePallets(DMExportOfflineContract[] lines, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateOfflinePallets", new object[] {
                        lines}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract[] EndUpdateOfflinePallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/TransferPalletsToNewLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public LocationHistory[] TransferPalletsToNewLocation([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")] LocationHistory[] lines) {
            object[] results = this.Invoke("TransferPalletsToNewLocation", new object[] {
                        lines});
            return ((LocationHistory[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransferPalletsToNewLocation(LocationHistory[] lines, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransferPalletsToNewLocation", new object[] {
                        lines}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocationHistory[] EndTransferPalletsToNewLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocationHistory[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/SummaryPallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
        public DMSummaryContract[] SummaryPallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId) {
            object[] results = this.Invoke("SummaryPallets", new object[] {
                        itemId});
            return ((DMSummaryContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSummaryPallets(string itemId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SummaryPallets", new object[] {
                        itemId}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMSummaryContract[] EndSummaryPallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMSummaryContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ItemGroupPallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
        public DMExportContract[] ItemGroupPallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string grade, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string shade, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string caliber) {
            object[] results = this.Invoke("ItemGroupPallets", new object[] {
                        itemId,
                        grade,
                        shade,
                        caliber});
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginItemGroupPallets(string itemId, string grade, string shade, string caliber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ItemGroupPallets", new object[] {
                        itemId,
                        grade,
                        shade,
                        caliber}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract[] EndItemGroupPallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/CreateDowntimeForMarpak", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDowntimeForMarpak(int whichMarpak, [System.Xml.Serialization.XmlIgnoreAttribute()] bool whichMarpakSpecified, out bool CreateDowntimeForMarpakResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateDowntimeForMarpakResultSpecified) {
            object[] results = this.Invoke("CreateDowntimeForMarpak", new object[] {
                        whichMarpak,
                        whichMarpakSpecified});
            CreateDowntimeForMarpakResult = ((bool)(results[0]));
            CreateDowntimeForMarpakResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateDowntimeForMarpak(int whichMarpak, bool whichMarpakSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateDowntimeForMarpak", new object[] {
                        whichMarpak,
                        whichMarpakSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateDowntimeForMarpak(System.IAsyncResult asyncResult, out bool CreateDowntimeForMarpakResult, out bool CreateDowntimeForMarpakResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CreateDowntimeForMarpakResult = ((bool)(results[0]));
            CreateDowntimeForMarpakResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetProductionByLinesForChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public ItemForChart[] GetProductionByLinesForChart(System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified) {
            object[] results = this.Invoke("GetProductionByLinesForChart", new object[] {
                        date,
                        dateSpecified});
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductionByLinesForChart(System.DateTime date, bool dateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductionByLinesForChart", new object[] {
                        date,
                        dateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemForChart[] EndGetProductionByLinesForChart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetProductionByItemsForChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public ItemForChart[] GetProductionByItemsForChart(System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified) {
            object[] results = this.Invoke("GetProductionByItemsForChart", new object[] {
                        date,
                        dateSpecified});
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductionByItemsForChart(System.DateTime date, bool dateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductionByItemsForChart", new object[] {
                        date,
                        dateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemForChart[] EndGetProductionByItemsForChart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetWHLocations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
        public WmsLocationContract[] GetWHLocations() {
            object[] results = this.Invoke("GetWHLocations", new object[0]);
            return ((WmsLocationContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWHLocations(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWHLocations", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WmsLocationContract[] EndGetWHLocations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WmsLocationContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetDuplicatePallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public DuplicatePallet[] GetDuplicatePallets() {
            object[] results = this.Invoke("GetDuplicatePallets", new object[0]);
            return ((DuplicatePallet[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDuplicatePallets(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDuplicatePallets", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public DuplicatePallet[] EndGetDuplicatePallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DuplicatePallet[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ClearDuplicatePallet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDuplicatePallet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DuplicatePallet pallet, out bool ClearDuplicatePalletResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClearDuplicatePalletResultSpecified) {
            object[] results = this.Invoke("ClearDuplicatePallet", new object[] {
                        pallet});
            ClearDuplicatePalletResult = ((bool)(results[0]));
            ClearDuplicatePalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearDuplicatePallet(DuplicatePallet pallet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearDuplicatePallet", new object[] {
                        pallet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClearDuplicatePallet(System.IAsyncResult asyncResult, out bool ClearDuplicatePalletResult, out bool ClearDuplicatePalletResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClearDuplicatePalletResult = ((bool)(results[0]));
            ClearDuplicatePalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ClearDuplicatePalletsAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDuplicatePalletsAll([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")] DuplicatePallet[] pallets, out bool ClearDuplicatePalletsAllResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClearDuplicatePalletsAllResultSpecified) {
            object[] results = this.Invoke("ClearDuplicatePalletsAll", new object[] {
                        pallets});
            ClearDuplicatePalletsAllResult = ((bool)(results[0]));
            ClearDuplicatePalletsAllResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearDuplicatePalletsAll(DuplicatePallet[] pallets, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearDuplicatePalletsAll", new object[] {
                        pallets}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClearDuplicatePalletsAll(System.IAsyncResult asyncResult, out bool ClearDuplicatePalletsAllResult, out bool ClearDuplicatePalletsAllResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClearDuplicatePalletsAllResult = ((bool)(results[0]));
            ClearDuplicatePalletsAllResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMExportContract : XppObjectBase {
        
        private string barCodePalletField;
        
        private int boxesOnPalletField;
        
        private bool boxesOnPalletFieldSpecified;
        
        private string caliberField;
        
        private System.DateTime cancelDateTimeField;
        
        private bool cancelDateTimeFieldSpecified;
        
        private bool codeLabelField;
        
        private bool codeLabelFieldSpecified;
        
        private string dMShortDescField;
        
        private string dMShortDesc2Field;
        
        private string deviceNameField;
        
        private string deviceUserField;
        
        private System.DateTime fGApprovalTimeField;
        
        private bool fGApprovalTimeFieldSpecified;
        
        private string gradeField;
        
        private bool isApprovedByFGField;
        
        private bool isApprovedByFGFieldSpecified;
        
        private bool isApprovedBySLField;
        
        private bool isApprovedBySLFieldSpecified;
        
        private bool isCancelledField;
        
        private bool isCancelledFieldSpecified;
        
        private bool isPostedField;
        
        private bool isPostedFieldSpecified;
        
        private string itemDescField;
        
        private string itemNumberField;
        
        private PalletTransportBy lGVOrForkliftField;
        
        private bool lGVOrForkliftFieldSpecified;
        
        private int lineOfOriginField;
        
        private bool lineOfOriginFieldSpecified;
        
        private long marpakMovNumField;
        
        private bool marpakMovNumFieldSpecified;
        
        private long movementNumberField;
        
        private bool movementNumberFieldSpecified;
        
        private string palletNumField;
        
        private int piecesForBoxField;
        
        private bool piecesForBoxFieldSpecified;
        
        private long recordIdField;
        
        private bool recordIdFieldSpecified;
        
        private string shadeField;
        
        private int shiftField;
        
        private bool shiftFieldSpecified;
        
        private System.DateTime shiftDateField;
        
        private bool shiftDateFieldSpecified;
        
        private string sizeField;
        
        private decimal surfaceMQBoxField;
        
        private bool surfaceMQBoxFieldSpecified;
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        private int totalPiecesOnPalletField;
        
        private bool totalPiecesOnPalletFieldSpecified;
        
        private decimal totalSurfaceField;
        
        private bool totalSurfaceFieldSpecified;
        
        private int whichMarpakField;
        
        private bool whichMarpakFieldSpecified;
        
        private string whLocationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BarCodePallet {
            get {
                return this.barCodePalletField;
            }
            set {
                this.barCodePalletField = value;
            }
        }
        
        /// <remarks/>
        public int BoxesOnPallet {
            get {
                return this.boxesOnPalletField;
            }
            set {
                this.boxesOnPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxesOnPalletSpecified {
            get {
                return this.boxesOnPalletFieldSpecified;
            }
            set {
                this.boxesOnPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Caliber {
            get {
                return this.caliberField;
            }
            set {
                this.caliberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CancelDateTime {
            get {
                return this.cancelDateTimeField;
            }
            set {
                this.cancelDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CancelDateTimeSpecified {
            get {
                return this.cancelDateTimeFieldSpecified;
            }
            set {
                this.cancelDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool CodeLabel {
            get {
                return this.codeLabelField;
            }
            set {
                this.codeLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeLabelSpecified {
            get {
                return this.codeLabelFieldSpecified;
            }
            set {
                this.codeLabelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DMShortDesc {
            get {
                return this.dMShortDescField;
            }
            set {
                this.dMShortDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DMShortDesc2 {
            get {
                return this.dMShortDesc2Field;
            }
            set {
                this.dMShortDesc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceUser {
            get {
                return this.deviceUserField;
            }
            set {
                this.deviceUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FGApprovalTime {
            get {
                return this.fGApprovalTimeField;
            }
            set {
                this.fGApprovalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FGApprovalTimeSpecified {
            get {
                return this.fGApprovalTimeFieldSpecified;
            }
            set {
                this.fGApprovalTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsApprovedByFG {
            get {
                return this.isApprovedByFGField;
            }
            set {
                this.isApprovedByFGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsApprovedByFGSpecified {
            get {
                return this.isApprovedByFGFieldSpecified;
            }
            set {
                this.isApprovedByFGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsApprovedBySL {
            get {
                return this.isApprovedBySLField;
            }
            set {
                this.isApprovedBySLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsApprovedBySLSpecified {
            get {
                return this.isApprovedBySLFieldSpecified;
            }
            set {
                this.isApprovedBySLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsCancelledSpecified {
            get {
                return this.isCancelledFieldSpecified;
            }
            set {
                this.isCancelledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsPosted {
            get {
                return this.isPostedField;
            }
            set {
                this.isPostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPostedSpecified {
            get {
                return this.isPostedFieldSpecified;
            }
            set {
                this.isPostedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public PalletTransportBy LGVOrForklift {
            get {
                return this.lGVOrForkliftField;
            }
            set {
                this.lGVOrForkliftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LGVOrForkliftSpecified {
            get {
                return this.lGVOrForkliftFieldSpecified;
            }
            set {
                this.lGVOrForkliftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int LineOfOrigin {
            get {
                return this.lineOfOriginField;
            }
            set {
                this.lineOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineOfOriginSpecified {
            get {
                return this.lineOfOriginFieldSpecified;
            }
            set {
                this.lineOfOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long MarpakMovNum {
            get {
                return this.marpakMovNumField;
            }
            set {
                this.marpakMovNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MarpakMovNumSpecified {
            get {
                return this.marpakMovNumFieldSpecified;
            }
            set {
                this.marpakMovNumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long MovementNumber {
            get {
                return this.movementNumberField;
            }
            set {
                this.movementNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MovementNumberSpecified {
            get {
                return this.movementNumberFieldSpecified;
            }
            set {
                this.movementNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        public int PiecesForBox {
            get {
                return this.piecesForBoxField;
            }
            set {
                this.piecesForBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PiecesForBoxSpecified {
            get {
                return this.piecesForBoxFieldSpecified;
            }
            set {
                this.piecesForBoxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIdSpecified {
            get {
                return this.recordIdFieldSpecified;
            }
            set {
                this.recordIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Shade {
            get {
                return this.shadeField;
            }
            set {
                this.shadeField = value;
            }
        }
        
        /// <remarks/>
        public int Shift {
            get {
                return this.shiftField;
            }
            set {
                this.shiftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShiftSpecified {
            get {
                return this.shiftFieldSpecified;
            }
            set {
                this.shiftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShiftDate {
            get {
                return this.shiftDateField;
            }
            set {
                this.shiftDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShiftDateSpecified {
            get {
                return this.shiftDateFieldSpecified;
            }
            set {
                this.shiftDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SurfaceMQBox {
            get {
                return this.surfaceMQBoxField;
            }
            set {
                this.surfaceMQBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurfaceMQBoxSpecified {
            get {
                return this.surfaceMQBoxFieldSpecified;
            }
            set {
                this.surfaceMQBoxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TotalPiecesOnPallet {
            get {
                return this.totalPiecesOnPalletField;
            }
            set {
                this.totalPiecesOnPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPiecesOnPalletSpecified {
            get {
                return this.totalPiecesOnPalletFieldSpecified;
            }
            set {
                this.totalPiecesOnPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalSurface {
            get {
                return this.totalSurfaceField;
            }
            set {
                this.totalSurfaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSurfaceSpecified {
            get {
                return this.totalSurfaceFieldSpecified;
            }
            set {
                this.totalSurfaceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WhichMarpak {
            get {
                return this.whichMarpakField;
            }
            set {
                this.whichMarpakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WhichMarpakSpecified {
            get {
                return this.whichMarpakFieldSpecified;
            }
            set {
                this.whichMarpakFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whLocationId {
            get {
                return this.whLocationIdField;
            }
            set {
                this.whLocationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PalletTransportBy {
        
        /// <remarks/>
        LGV,
        
        /// <remarks/>
        Forklift,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportMiniContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMForTransfer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportOfflineContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMSummaryContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportItemNumContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WmsLocationContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemCodeContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportContract))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public partial class XppObjectBase : ProxyBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XppObjectBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportMiniContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMForTransfer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportOfflineContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMSummaryContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportItemNumContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WmsLocationContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemCodeContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportContract))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    public partial class ProxyBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class DuplicatePallet {
        
        private System.Nullable<System.DateTime> createdDateTimeField;
        
        private bool createdDateTimeFieldSpecified;
        
        private string itemArticleField;
        
        private string palletNumField;
        
        private int recordIdField;
        
        private bool recordIdFieldSpecified;
        
        private int whichMarpakField;
        
        private bool whichMarpakFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDateTime {
            get {
                return this.createdDateTimeField;
            }
            set {
                this.createdDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified {
            get {
                return this.createdDateTimeFieldSpecified;
            }
            set {
                this.createdDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemArticle {
            get {
                return this.itemArticleField;
            }
            set {
                this.itemArticleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        public int RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIdSpecified {
            get {
                return this.recordIdFieldSpecified;
            }
            set {
                this.recordIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WhichMarpak {
            get {
                return this.whichMarpakField;
            }
            set {
                this.whichMarpakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WhichMarpakSpecified {
            get {
                return this.whichMarpakFieldSpecified;
            }
            set {
                this.whichMarpakFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class ItemForChart {
        
        private int boxesOnPalletField;
        
        private bool boxesOnPalletFieldSpecified;
        
        private string descGradeField;
        
        private string itemArticleField;
        
        private string itemDescField;
        
        private string lineNameField;
        
        private int lineOfOriginField;
        
        private bool lineOfOriginFieldSpecified;
        
        private decimal sQMField;
        
        private bool sQMFieldSpecified;
        
        /// <remarks/>
        public int BoxesOnPallet {
            get {
                return this.boxesOnPalletField;
            }
            set {
                this.boxesOnPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxesOnPalletSpecified {
            get {
                return this.boxesOnPalletFieldSpecified;
            }
            set {
                this.boxesOnPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescGrade {
            get {
                return this.descGradeField;
            }
            set {
                this.descGradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemArticle {
            get {
                return this.itemArticleField;
            }
            set {
                this.itemArticleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LineName {
            get {
                return this.lineNameField;
            }
            set {
                this.lineNameField = value;
            }
        }
        
        /// <remarks/>
        public int LineOfOrigin {
            get {
                return this.lineOfOriginField;
            }
            set {
                this.lineOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineOfOriginSpecified {
            get {
                return this.lineOfOriginFieldSpecified;
            }
            set {
                this.lineOfOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SQM {
            get {
                return this.sQMField;
            }
            set {
                this.sQMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SQMSpecified {
            get {
                return this.sQMFieldSpecified;
            }
            set {
                this.sQMFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class LocationHistory {
        
        private System.DateTime createDateTimeField;
        
        private bool createDateTimeFieldSpecified;
        
        private string deviceNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isManualField;
        
        private bool isManualFieldSpecified;
        
        private string locationField;
        
        private string messageField;
        
        private string palletNumField;
        
        private string quantityField;
        
        private string userNameField;
        
        /// <remarks/>
        public System.DateTime CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateTimeSpecified {
            get {
                return this.createDateTimeFieldSpecified;
            }
            set {
                this.createDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsManual {
            get {
                return this.isManualField;
            }
            set {
                this.isManualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsManualSpecified {
            get {
                return this.isManualFieldSpecified;
            }
            set {
                this.isManualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMExportMiniContract : XppObjectBase {
        
        private string barCodePalletField;
        
        private string dMShortDescField;
        
        private string dMShortDesc2Field;
        
        private string palletNumField;
        
        private long recordIdField;
        
        private bool recordIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BarCodePallet {
            get {
                return this.barCodePalletField;
            }
            set {
                this.barCodePalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DMShortDesc {
            get {
                return this.dMShortDescField;
            }
            set {
                this.dMShortDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DMShortDesc2 {
            get {
                return this.dMShortDesc2Field;
            }
            set {
                this.dMShortDesc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        public long RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIdSpecified {
            get {
                return this.recordIdFieldSpecified;
            }
            set {
                this.recordIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMForTransfer : XppObjectBase {
        
        private bool isPostedField;
        
        private bool isPostedFieldSpecified;
        
        private bool isTransferredField;
        
        private bool isTransferredFieldSpecified;
        
        private string palletNumField;
        
        private string whLocationIdField;
        
        /// <remarks/>
        public bool IsPosted {
            get {
                return this.isPostedField;
            }
            set {
                this.isPostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPostedSpecified {
            get {
                return this.isPostedFieldSpecified;
            }
            set {
                this.isPostedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsTransferred {
            get {
                return this.isTransferredField;
            }
            set {
                this.isTransferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTransferredSpecified {
            get {
                return this.isTransferredFieldSpecified;
            }
            set {
                this.isTransferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whLocationId {
            get {
                return this.whLocationIdField;
            }
            set {
                this.whLocationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMExportOfflineContract : XppObjectBase {
        
        private decimal boxesOnPalletField;
        
        private bool boxesOnPalletFieldSpecified;
        
        private string caliberField;
        
        private string deviceNameField;
        
        private string deviceUserField;
        
        private string gradeField;
        
        private bool isApprovedByFGField;
        
        private bool isApprovedByFGFieldSpecified;
        
        private bool isApprovedBySLField;
        
        private bool isApprovedBySLFieldSpecified;
        
        private NoYes isOfflineModeField;
        
        private bool isOfflineModeFieldSpecified;
        
        private string palletNumField;
        
        private string shadeField;
        
        private string whLocationIdField;
        
        /// <remarks/>
        public decimal BoxesOnPallet {
            get {
                return this.boxesOnPalletField;
            }
            set {
                this.boxesOnPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxesOnPalletSpecified {
            get {
                return this.boxesOnPalletFieldSpecified;
            }
            set {
                this.boxesOnPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Caliber {
            get {
                return this.caliberField;
            }
            set {
                this.caliberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceUser {
            get {
                return this.deviceUserField;
            }
            set {
                this.deviceUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsApprovedByFG {
            get {
                return this.isApprovedByFGField;
            }
            set {
                this.isApprovedByFGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsApprovedByFGSpecified {
            get {
                return this.isApprovedByFGFieldSpecified;
            }
            set {
                this.isApprovedByFGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsApprovedBySL {
            get {
                return this.isApprovedBySLField;
            }
            set {
                this.isApprovedBySLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsApprovedBySLSpecified {
            get {
                return this.isApprovedBySLFieldSpecified;
            }
            set {
                this.isApprovedBySLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public NoYes IsOfflineMode {
            get {
                return this.isOfflineModeField;
            }
            set {
                this.isOfflineModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOfflineModeSpecified {
            get {
                return this.isOfflineModeFieldSpecified;
            }
            set {
                this.isOfflineModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Shade {
            get {
                return this.shadeField;
            }
            set {
                this.shadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whLocationId {
            get {
                return this.whLocationIdField;
            }
            set {
                this.whLocationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMSummaryContract : XppObjectBase {
        
        private string caliberField;
        
        private string gradeField;
        
        private string itemDescriptionField;
        
        private string itemNumberField;
        
        private int numOfPalletsField;
        
        private bool numOfPalletsFieldSpecified;
        
        private int numOfPalletsApprovedField;
        
        private bool numOfPalletsApprovedFieldSpecified;
        
        private int numOfPalletsPostedField;
        
        private bool numOfPalletsPostedFieldSpecified;
        
        private string shadeField;
        
        private decimal totalQtyField;
        
        private bool totalQtyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Caliber {
            get {
                return this.caliberField;
            }
            set {
                this.caliberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfPallets {
            get {
                return this.numOfPalletsField;
            }
            set {
                this.numOfPalletsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumOfPalletsSpecified {
            get {
                return this.numOfPalletsFieldSpecified;
            }
            set {
                this.numOfPalletsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NumOfPalletsApproved {
            get {
                return this.numOfPalletsApprovedField;
            }
            set {
                this.numOfPalletsApprovedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumOfPalletsApprovedSpecified {
            get {
                return this.numOfPalletsApprovedFieldSpecified;
            }
            set {
                this.numOfPalletsApprovedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NumOfPalletsPosted {
            get {
                return this.numOfPalletsPostedField;
            }
            set {
                this.numOfPalletsPostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumOfPalletsPostedSpecified {
            get {
                return this.numOfPalletsPostedFieldSpecified;
            }
            set {
                this.numOfPalletsPostedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Shade {
            get {
                return this.shadeField;
            }
            set {
                this.shadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalQty {
            get {
                return this.totalQtyField;
            }
            set {
                this.totalQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalQtySpecified {
            get {
                return this.totalQtyFieldSpecified;
            }
            set {
                this.totalQtyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class DMExportItemNumContract : XppObjectBase {
        
        private System.DateTime dateSaveField;
        
        private bool dateSaveFieldSpecified;
        
        private int hasProcessedField;
        
        private bool hasProcessedFieldSpecified;
        
        private string itemNumberField;
        
        /// <remarks/>
        public System.DateTime DateSave {
            get {
                return this.dateSaveField;
            }
            set {
                this.dateSaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSaveSpecified {
            get {
                return this.dateSaveFieldSpecified;
            }
            set {
                this.dateSaveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int HasProcessed {
            get {
                return this.hasProcessedField;
            }
            set {
                this.hasProcessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasProcessedSpecified {
            get {
                return this.hasProcessedFieldSpecified;
            }
            set {
                this.hasProcessedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class WmsLocationContract : XppObjectBase {
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public partial class ItemCodeContract : XppObjectBase {
        
        private decimal boxPerPalletField;
        
        private bool boxPerPalletFieldSpecified;
        
        private string desc1Field;
        
        private string desc2Field;
        
        private string itemNumberField;
        
        private string sizeField;
        
        private decimal sqmPerBoxField;
        
        private bool sqmPerBoxFieldSpecified;
        
        private decimal tilesPerBoxField;
        
        private bool tilesPerBoxFieldSpecified;
        
        /// <remarks/>
        public decimal BoxPerPallet {
            get {
                return this.boxPerPalletField;
            }
            set {
                this.boxPerPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxPerPalletSpecified {
            get {
                return this.boxPerPalletFieldSpecified;
            }
            set {
                this.boxPerPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Desc1 {
            get {
                return this.desc1Field;
            }
            set {
                this.desc1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Desc2 {
            get {
                return this.desc2Field;
            }
            set {
                this.desc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SqmPerBox {
            get {
                return this.sqmPerBoxField;
            }
            set {
                this.sqmPerBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SqmPerBoxSpecified {
            get {
                return this.sqmPerBoxFieldSpecified;
            }
            set {
                this.sqmPerBoxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TilesPerBox {
            get {
                return this.tilesPerBoxField;
            }
            set {
                this.tilesPerBoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TilesPerBoxSpecified {
            get {
                return this.tilesPerBoxFieldSpecified;
            }
            set {
                this.tilesPerBoxFieldSpecified = value;
            }
        }
    }
}
