//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace PalletReceive.DMServices {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDMCheckService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Delegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XppObjectBase))]
    public partial class DMCheckService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DMCheckService() {
            this.Url = "http://172.17.0.50/HandHeldServices/DMCheckService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetPing() {
            object[] results = this.Invoke("GetPing", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPing", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPalletInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DMExportContract GetPalletInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum) {
            object[] results = this.Invoke("GetPalletInfo", new object[] {
                        palletNum});
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPalletInfo(string palletNum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPalletInfo", new object[] {
                        palletNum}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract EndGetPalletInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetPalletInfoByRecordId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DMExportContract GetPalletInfoByRecordId(long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified) {
            object[] results = this.Invoke("GetPalletInfoByRecordId", new object[] {
                        recordId,
                        recordIdSpecified});
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPalletInfoByRecordId(long recordId, bool recordIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPalletInfoByRecordId", new object[] {
                        recordId,
                        recordIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract EndGetPalletInfoByRecordId(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ConfirmPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConfirmPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, bool isFromSL, [System.Xml.Serialization.XmlIgnoreAttribute()] bool isFromSLSpecified, out bool ConfirmPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ConfirmPalletReceiveResultSpecified) {
            object[] results = this.Invoke("ConfirmPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified});
            ConfirmPalletReceiveResult = ((bool)(results[0]));
            ConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConfirmPalletReceive(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, bool isFromSL, bool isFromSLSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConfirmPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndConfirmPalletReceive(System.IAsyncResult asyncResult, out bool ConfirmPalletReceiveResult, out bool ConfirmPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ConfirmPalletReceiveResult = ((bool)(results[0]));
            ConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ConfirmPalletAndLocationReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmPalletAndLocationReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationId, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, bool isFromSL, [System.Xml.Serialization.XmlIgnoreAttribute()] bool isFromSLSpecified) {
            object[] results = this.Invoke("ConfirmPalletAndLocationReceive", new object[] {
                        palletNum,
                        locationId,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConfirmPalletAndLocationReceive(string palletNum, string locationId, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, bool isFromSL, bool isFromSLSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConfirmPalletAndLocationReceive", new object[] {
                        palletNum,
                        locationId,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser,
                        isFromSL,
                        isFromSLSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndConfirmPalletAndLocationReceive(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/CancelPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, out bool CancelPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CancelPalletReceiveResultSpecified) {
            object[] results = this.Invoke("CancelPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser});
            CancelPalletReceiveResult = ((bool)(results[0]));
            CancelPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCancelPalletReceive(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CancelPalletReceive", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCancelPalletReceive(System.IAsyncResult asyncResult, out bool CancelPalletReceiveResult, out bool CancelPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CancelPalletReceiveResult = ((bool)(results[0]));
            CancelPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/UpdateAndConfirmPalletReceive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateAndConfirmPalletReceive([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DMExportContract pallet, out bool UpdateAndConfirmPalletReceiveResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateAndConfirmPalletReceiveResultSpecified) {
            object[] results = this.Invoke("UpdateAndConfirmPalletReceive", new object[] {
                        pallet});
            UpdateAndConfirmPalletReceiveResult = ((bool)(results[0]));
            UpdateAndConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateAndConfirmPalletReceive(DMExportContract pallet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateAndConfirmPalletReceive", new object[] {
                        pallet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateAndConfirmPalletReceive(System.IAsyncResult asyncResult, out bool UpdateAndConfirmPalletReceiveResult, out bool UpdateAndConfirmPalletReceiveResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            UpdateAndConfirmPalletReceiveResult = ((bool)(results[0]));
            UpdateAndConfirmPalletReceiveResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/PrintAgainPallet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PrintAgainPallet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string palletNum, long recordId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool recordIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string deviceUser, out bool PrintAgainPalletResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool PrintAgainPalletResultSpecified) {
            object[] results = this.Invoke("PrintAgainPallet", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser});
            PrintAgainPalletResult = ((bool)(results[0]));
            PrintAgainPalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPrintAgainPallet(string palletNum, long recordId, bool recordIdSpecified, string deviceName, string deviceUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("PrintAgainPallet", new object[] {
                        palletNum,
                        recordId,
                        recordIdSpecified,
                        deviceName,
                        deviceUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndPrintAgainPallet(System.IAsyncResult asyncResult, out bool PrintAgainPalletResult, out bool PrintAgainPalletResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            PrintAgainPalletResult = ((bool)(results[0]));
            PrintAgainPalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/DMClearPrintAgain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
        public DMExportMiniContract[] DMClearPrintAgain() {
            object[] results = this.Invoke("DMClearPrintAgain", new object[0]);
            return ((DMExportMiniContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDMClearPrintAgain(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DMClearPrintAgain", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportMiniContract[] EndDMClearPrintAgain(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportMiniContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/UpdateOfflinePallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
        public DMExportContract[] UpdateOfflinePallets([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")] DMExportOfflineContract[] lines) {
            object[] results = this.Invoke("UpdateOfflinePallets", new object[] {
                        lines});
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateOfflinePallets(DMExportOfflineContract[] lines, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateOfflinePallets", new object[] {
                        lines}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract[] EndUpdateOfflinePallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/TransferPalletsToNewLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public LocationHistory[] TransferPalletsToNewLocation([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")] LocationHistory[] lines) {
            object[] results = this.Invoke("TransferPalletsToNewLocation", new object[] {
                        lines});
            return ((LocationHistory[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransferPalletsToNewLocation(LocationHistory[] lines, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransferPalletsToNewLocation", new object[] {
                        lines}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocationHistory[] EndTransferPalletsToNewLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocationHistory[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/SummaryPallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
        public DMSummaryContract[] SummaryPallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId) {
            object[] results = this.Invoke("SummaryPallets", new object[] {
                        itemId});
            return ((DMSummaryContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSummaryPallets(string itemId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SummaryPallets", new object[] {
                        itemId}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMSummaryContract[] EndSummaryPallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMSummaryContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ItemGroupPallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
        public DMExportContract[] ItemGroupPallets([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string grade, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string shade, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string caliber) {
            object[] results = this.Invoke("ItemGroupPallets", new object[] {
                        itemId,
                        grade,
                        shade,
                        caliber});
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginItemGroupPallets(string itemId, string grade, string shade, string caliber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ItemGroupPallets", new object[] {
                        itemId,
                        grade,
                        shade,
                        caliber}, callback, asyncState);
        }
        
        /// <remarks/>
        public DMExportContract[] EndItemGroupPallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DMExportContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/CreateDowntimeForMarpak", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDowntimeForMarpak(int whichMarpak, [System.Xml.Serialization.XmlIgnoreAttribute()] bool whichMarpakSpecified, out bool CreateDowntimeForMarpakResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CreateDowntimeForMarpakResultSpecified) {
            object[] results = this.Invoke("CreateDowntimeForMarpak", new object[] {
                        whichMarpak,
                        whichMarpakSpecified});
            CreateDowntimeForMarpakResult = ((bool)(results[0]));
            CreateDowntimeForMarpakResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateDowntimeForMarpak(int whichMarpak, bool whichMarpakSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateDowntimeForMarpak", new object[] {
                        whichMarpak,
                        whichMarpakSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateDowntimeForMarpak(System.IAsyncResult asyncResult, out bool CreateDowntimeForMarpakResult, out bool CreateDowntimeForMarpakResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            CreateDowntimeForMarpakResult = ((bool)(results[0]));
            CreateDowntimeForMarpakResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetProductionByLinesForChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public ItemForChart[] GetProductionByLinesForChart(System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified) {
            object[] results = this.Invoke("GetProductionByLinesForChart", new object[] {
                        date,
                        dateSpecified});
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductionByLinesForChart(System.DateTime date, bool dateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductionByLinesForChart", new object[] {
                        date,
                        dateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemForChart[] EndGetProductionByLinesForChart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetProductionByItemsForChart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public ItemForChart[] GetProductionByItemsForChart(System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified) {
            object[] results = this.Invoke("GetProductionByItemsForChart", new object[] {
                        date,
                        dateSpecified});
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProductionByItemsForChart(System.DateTime date, bool dateSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProductionByItemsForChart", new object[] {
                        date,
                        dateSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemForChart[] EndGetProductionByItemsForChart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemForChart[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetWHLocations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
        public WmsLocationContract[] GetWHLocations() {
            object[] results = this.Invoke("GetWHLocations", new object[0]);
            return ((WmsLocationContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWHLocations(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWHLocations", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WmsLocationContract[] EndGetWHLocations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WmsLocationContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/GetDuplicatePallets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public DuplicatePallet[] GetDuplicatePallets() {
            object[] results = this.Invoke("GetDuplicatePallets", new object[0]);
            return ((DuplicatePallet[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDuplicatePallets(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDuplicatePallets", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public DuplicatePallet[] EndGetDuplicatePallets(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DuplicatePallet[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ClearDuplicatePallet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDuplicatePallet([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] DuplicatePallet pallet, out bool ClearDuplicatePalletResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClearDuplicatePalletResultSpecified) {
            object[] results = this.Invoke("ClearDuplicatePallet", new object[] {
                        pallet});
            ClearDuplicatePalletResult = ((bool)(results[0]));
            ClearDuplicatePalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearDuplicatePallet(DuplicatePallet pallet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearDuplicatePallet", new object[] {
                        pallet}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClearDuplicatePallet(System.IAsyncResult asyncResult, out bool ClearDuplicatePalletResult, out bool ClearDuplicatePalletResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClearDuplicatePalletResult = ((bool)(results[0]));
            ClearDuplicatePalletResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDMCheckService/ClearDuplicatePalletsAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearDuplicatePalletsAll([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")] DuplicatePallet[] pallets, out bool ClearDuplicatePalletsAllResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClearDuplicatePalletsAllResultSpecified) {
            object[] results = this.Invoke("ClearDuplicatePalletsAll", new object[] {
                        pallets});
            ClearDuplicatePalletsAllResult = ((bool)(results[0]));
            ClearDuplicatePalletsAllResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClearDuplicatePalletsAll(DuplicatePallet[] pallets, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClearDuplicatePalletsAll", new object[] {
                        pallets}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClearDuplicatePalletsAll(System.IAsyncResult asyncResult, out bool ClearDuplicatePalletsAllResult, out bool ClearDuplicatePalletsAllResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClearDuplicatePalletsAllResult = ((bool)(results[0]));
            ClearDuplicatePalletsAllResultSpecified = ((bool)(results[1]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class DMExportContract : XppObjectBase {
        
        private string barCodePalletFieldField;
        
        private int boxesOnPalletFieldField;
        
        private bool boxesOnPalletFieldSpecified1Field;
        
        private string caliberFieldField;
        
        private System.DateTime cancelDateTimeFieldField;
        
        private bool cancelDateTimeFieldSpecified1Field;
        
        private bool codeLabelFieldField;
        
        private bool codeLabelFieldSpecified1Field;
        
        private string dMShortDesc2FieldField;
        
        private string dMShortDescFieldField;
        
        private string deviceNameFieldField;
        
        private string deviceUserFieldField;
        
        private System.DateTime fGApprovalTimeFieldField;
        
        private bool fGApprovalTimeFieldSpecified1Field;
        
        private string gradeFieldField;
        
        private bool isApprovedByFGFieldField;
        
        private bool isApprovedByFGFieldSpecified1Field;
        
        private bool isApprovedBySLFieldField;
        
        private bool isApprovedBySLFieldSpecified1Field;
        
        private bool isCancelledFieldField;
        
        private bool isCancelledFieldSpecified1Field;
        
        private bool isPostedFieldField;
        
        private bool isPostedFieldSpecified1Field;
        
        private string itemDescFieldField;
        
        private string itemNumberFieldField;
        
        private PalletTransportBy lGVOrForkliftFieldField;
        
        private bool lGVOrForkliftFieldSpecified1Field;
        
        private int lineOfOriginFieldField;
        
        private bool lineOfOriginFieldSpecified1Field;
        
        private long marpakMovNumFieldField;
        
        private bool marpakMovNumFieldSpecified1Field;
        
        private long movementNumberFieldField;
        
        private bool movementNumberFieldSpecified1Field;
        
        private string palletNumFieldField;
        
        private int piecesForBoxFieldField;
        
        private bool piecesForBoxFieldSpecified1Field;
        
        private long recordIdFieldField;
        
        private bool recordIdFieldSpecified1Field;
        
        private string shadeFieldField;
        
        private System.DateTime shiftDateFieldField;
        
        private bool shiftDateFieldSpecified1Field;
        
        private int shiftFieldField;
        
        private bool shiftFieldSpecified1Field;
        
        private string sizeFieldField;
        
        private decimal surfaceMQBoxFieldField;
        
        private bool surfaceMQBoxFieldSpecified1Field;
        
        private System.DateTime timeStampFieldField;
        
        private bool timeStampFieldSpecified1Field;
        
        private int totalPiecesOnPalletFieldField;
        
        private bool totalPiecesOnPalletFieldSpecified1Field;
        
        private decimal totalSurfaceFieldField;
        
        private bool totalSurfaceFieldSpecified1Field;
        
        private string whLocationIdFieldField;
        
        private int whichMarpakFieldField;
        
        private bool whichMarpakFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string barCodePalletField {
            get {
                return this.barCodePalletFieldField;
            }
            set {
                this.barCodePalletFieldField = value;
            }
        }
        
        /// <remarks/>
        public int boxesOnPalletField {
            get {
                return this.boxesOnPalletFieldField;
            }
            set {
                this.boxesOnPalletFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boxesOnPalletFieldSpecified")]
        public bool boxesOnPalletFieldSpecified1 {
            get {
                return this.boxesOnPalletFieldSpecified1Field;
            }
            set {
                this.boxesOnPalletFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caliberField {
            get {
                return this.caliberFieldField;
            }
            set {
                this.caliberFieldField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cancelDateTimeField {
            get {
                return this.cancelDateTimeFieldField;
            }
            set {
                this.cancelDateTimeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cancelDateTimeFieldSpecified")]
        public bool cancelDateTimeFieldSpecified1 {
            get {
                return this.cancelDateTimeFieldSpecified1Field;
            }
            set {
                this.cancelDateTimeFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public bool codeLabelField {
            get {
                return this.codeLabelFieldField;
            }
            set {
                this.codeLabelFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codeLabelFieldSpecified")]
        public bool codeLabelFieldSpecified1 {
            get {
                return this.codeLabelFieldSpecified1Field;
            }
            set {
                this.codeLabelFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dMShortDesc2Field {
            get {
                return this.dMShortDesc2FieldField;
            }
            set {
                this.dMShortDesc2FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dMShortDescField {
            get {
                return this.dMShortDescFieldField;
            }
            set {
                this.dMShortDescFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deviceNameField {
            get {
                return this.deviceNameFieldField;
            }
            set {
                this.deviceNameFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deviceUserField {
            get {
                return this.deviceUserFieldField;
            }
            set {
                this.deviceUserFieldField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fGApprovalTimeField {
            get {
                return this.fGApprovalTimeFieldField;
            }
            set {
                this.fGApprovalTimeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fGApprovalTimeFieldSpecified")]
        public bool fGApprovalTimeFieldSpecified1 {
            get {
                return this.fGApprovalTimeFieldSpecified1Field;
            }
            set {
                this.fGApprovalTimeFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                this.gradeFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool isApprovedByFGField {
            get {
                return this.isApprovedByFGFieldField;
            }
            set {
                this.isApprovedByFGFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isApprovedByFGFieldSpecified")]
        public bool isApprovedByFGFieldSpecified1 {
            get {
                return this.isApprovedByFGFieldSpecified1Field;
            }
            set {
                this.isApprovedByFGFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public bool isApprovedBySLField {
            get {
                return this.isApprovedBySLFieldField;
            }
            set {
                this.isApprovedBySLFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isApprovedBySLFieldSpecified")]
        public bool isApprovedBySLFieldSpecified1 {
            get {
                return this.isApprovedBySLFieldSpecified1Field;
            }
            set {
                this.isApprovedBySLFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public bool isCancelledField {
            get {
                return this.isCancelledFieldField;
            }
            set {
                this.isCancelledFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isCancelledFieldSpecified")]
        public bool isCancelledFieldSpecified1 {
            get {
                return this.isCancelledFieldSpecified1Field;
            }
            set {
                this.isCancelledFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public bool isPostedField {
            get {
                return this.isPostedFieldField;
            }
            set {
                this.isPostedFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isPostedFieldSpecified")]
        public bool isPostedFieldSpecified1 {
            get {
                return this.isPostedFieldSpecified1Field;
            }
            set {
                this.isPostedFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemDescField {
            get {
                return this.itemDescFieldField;
            }
            set {
                this.itemDescFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemNumberField {
            get {
                return this.itemNumberFieldField;
            }
            set {
                this.itemNumberFieldField = value;
            }
        }
        
        /// <remarks/>
        public PalletTransportBy lGVOrForkliftField {
            get {
                return this.lGVOrForkliftFieldField;
            }
            set {
                this.lGVOrForkliftFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lGVOrForkliftFieldSpecified")]
        public bool lGVOrForkliftFieldSpecified1 {
            get {
                return this.lGVOrForkliftFieldSpecified1Field;
            }
            set {
                this.lGVOrForkliftFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int lineOfOriginField {
            get {
                return this.lineOfOriginFieldField;
            }
            set {
                this.lineOfOriginFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineOfOriginFieldSpecified")]
        public bool lineOfOriginFieldSpecified1 {
            get {
                return this.lineOfOriginFieldSpecified1Field;
            }
            set {
                this.lineOfOriginFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public long marpakMovNumField {
            get {
                return this.marpakMovNumFieldField;
            }
            set {
                this.marpakMovNumFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("marpakMovNumFieldSpecified")]
        public bool marpakMovNumFieldSpecified1 {
            get {
                return this.marpakMovNumFieldSpecified1Field;
            }
            set {
                this.marpakMovNumFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public long movementNumberField {
            get {
                return this.movementNumberFieldField;
            }
            set {
                this.movementNumberFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movementNumberFieldSpecified")]
        public bool movementNumberFieldSpecified1 {
            get {
                return this.movementNumberFieldSpecified1Field;
            }
            set {
                this.movementNumberFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string palletNumField {
            get {
                return this.palletNumFieldField;
            }
            set {
                this.palletNumFieldField = value;
            }
        }
        
        /// <remarks/>
        public int piecesForBoxField {
            get {
                return this.piecesForBoxFieldField;
            }
            set {
                this.piecesForBoxFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("piecesForBoxFieldSpecified")]
        public bool piecesForBoxFieldSpecified1 {
            get {
                return this.piecesForBoxFieldSpecified1Field;
            }
            set {
                this.piecesForBoxFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public long recordIdField {
            get {
                return this.recordIdFieldField;
            }
            set {
                this.recordIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordIdFieldSpecified")]
        public bool recordIdFieldSpecified1 {
            get {
                return this.recordIdFieldSpecified1Field;
            }
            set {
                this.recordIdFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shadeField {
            get {
                return this.shadeFieldField;
            }
            set {
                this.shadeFieldField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime shiftDateField {
            get {
                return this.shiftDateFieldField;
            }
            set {
                this.shiftDateFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shiftDateFieldSpecified")]
        public bool shiftDateFieldSpecified1 {
            get {
                return this.shiftDateFieldSpecified1Field;
            }
            set {
                this.shiftDateFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int shiftField {
            get {
                return this.shiftFieldField;
            }
            set {
                this.shiftFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shiftFieldSpecified")]
        public bool shiftFieldSpecified1 {
            get {
                return this.shiftFieldSpecified1Field;
            }
            set {
                this.shiftFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sizeField {
            get {
                return this.sizeFieldField;
            }
            set {
                this.sizeFieldField = value;
            }
        }
        
        /// <remarks/>
        public decimal surfaceMQBoxField {
            get {
                return this.surfaceMQBoxFieldField;
            }
            set {
                this.surfaceMQBoxFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("surfaceMQBoxFieldSpecified")]
        public bool surfaceMQBoxFieldSpecified1 {
            get {
                return this.surfaceMQBoxFieldSpecified1Field;
            }
            set {
                this.surfaceMQBoxFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timeStampField {
            get {
                return this.timeStampFieldField;
            }
            set {
                this.timeStampFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("timeStampFieldSpecified")]
        public bool timeStampFieldSpecified1 {
            get {
                return this.timeStampFieldSpecified1Field;
            }
            set {
                this.timeStampFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int totalPiecesOnPalletField {
            get {
                return this.totalPiecesOnPalletFieldField;
            }
            set {
                this.totalPiecesOnPalletFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totalPiecesOnPalletFieldSpecified")]
        public bool totalPiecesOnPalletFieldSpecified1 {
            get {
                return this.totalPiecesOnPalletFieldSpecified1Field;
            }
            set {
                this.totalPiecesOnPalletFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal totalSurfaceField {
            get {
                return this.totalSurfaceFieldField;
            }
            set {
                this.totalSurfaceFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totalSurfaceFieldSpecified")]
        public bool totalSurfaceFieldSpecified1 {
            get {
                return this.totalSurfaceFieldSpecified1Field;
            }
            set {
                this.totalSurfaceFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whLocationIdField {
            get {
                return this.whLocationIdFieldField;
            }
            set {
                this.whLocationIdFieldField = value;
            }
        }
        
        /// <remarks/>
        public int whichMarpakField {
            get {
                return this.whichMarpakFieldField;
            }
            set {
                this.whichMarpakFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("whichMarpakFieldSpecified")]
        public bool whichMarpakFieldSpecified1 {
            get {
                return this.whichMarpakFieldSpecified1Field;
            }
            set {
                this.whichMarpakFieldSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public enum PalletTransportBy {
        
        /// <remarks/>
        LGV,
        
        /// <remarks/>
        Forklift,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WmsLocationContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMSummaryContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportOfflineContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportMiniContract))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DMExportContract))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class XppObjectBase {
        
        private PropertyChangedEventHandler propertyChangedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PropertyChangedEventHandler PropertyChanged {
            get {
                return this.propertyChangedField;
            }
            set {
                this.propertyChangedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.ComponentModel")]
    public partial class PropertyChangedEventHandler : MulticastDelegate {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class MulticastDelegate : Delegate {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MulticastDelegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Delegate {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class DuplicatePallet {
        
        private System.Nullable<System.DateTime> createdDateTimeField;
        
        private bool createdDateTimeFieldSpecified;
        
        private string itemArticleField;
        
        private string palletNumField;
        
        private int recordIdField;
        
        private bool recordIdFieldSpecified;
        
        private int whichMarpakField;
        
        private bool whichMarpakFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDateTime {
            get {
                return this.createdDateTimeField;
            }
            set {
                this.createdDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedDateTimeSpecified {
            get {
                return this.createdDateTimeFieldSpecified;
            }
            set {
                this.createdDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemArticle {
            get {
                return this.itemArticleField;
            }
            set {
                this.itemArticleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        public int RecordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIdSpecified {
            get {
                return this.recordIdFieldSpecified;
            }
            set {
                this.recordIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WhichMarpak {
            get {
                return this.whichMarpakField;
            }
            set {
                this.whichMarpakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WhichMarpakSpecified {
            get {
                return this.whichMarpakFieldSpecified;
            }
            set {
                this.whichMarpakFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class ItemForChart {
        
        private int boxesOnPalletField;
        
        private bool boxesOnPalletFieldSpecified;
        
        private string descGradeField;
        
        private string itemArticleField;
        
        private string itemDescField;
        
        private string lineNameField;
        
        private int lineOfOriginField;
        
        private bool lineOfOriginFieldSpecified;
        
        private decimal sQMField;
        
        private bool sQMFieldSpecified;
        
        /// <remarks/>
        public int BoxesOnPallet {
            get {
                return this.boxesOnPalletField;
            }
            set {
                this.boxesOnPalletField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxesOnPalletSpecified {
            get {
                return this.boxesOnPalletFieldSpecified;
            }
            set {
                this.boxesOnPalletFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescGrade {
            get {
                return this.descGradeField;
            }
            set {
                this.descGradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemArticle {
            get {
                return this.itemArticleField;
            }
            set {
                this.itemArticleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemDesc {
            get {
                return this.itemDescField;
            }
            set {
                this.itemDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LineName {
            get {
                return this.lineNameField;
            }
            set {
                this.lineNameField = value;
            }
        }
        
        /// <remarks/>
        public int LineOfOrigin {
            get {
                return this.lineOfOriginField;
            }
            set {
                this.lineOfOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineOfOriginSpecified {
            get {
                return this.lineOfOriginFieldSpecified;
            }
            set {
                this.lineOfOriginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SQM {
            get {
                return this.sQMField;
            }
            set {
                this.sQMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SQMSpecified {
            get {
                return this.sQMFieldSpecified;
            }
            set {
                this.sQMFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class LocationHistory {
        
        private System.DateTime createDateTimeField;
        
        private bool createDateTimeFieldSpecified;
        
        private string deviceNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isManualField;
        
        private bool isManualFieldSpecified;
        
        private string locationField;
        
        private string messageField;
        
        private string palletNumField;
        
        private string quantityField;
        
        private string userNameField;
        
        /// <remarks/>
        public System.DateTime CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateTimeSpecified {
            get {
                return this.createDateTimeFieldSpecified;
            }
            set {
                this.createDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsManual {
            get {
                return this.isManualField;
            }
            set {
                this.isManualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsManualSpecified {
            get {
                return this.isManualFieldSpecified;
            }
            set {
                this.isManualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PalletNum {
            get {
                return this.palletNumField;
            }
            set {
                this.palletNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class WmsLocationContract : XppObjectBase {
        
        private string locationFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locationField {
            get {
                return this.locationFieldField;
            }
            set {
                this.locationFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class DMSummaryContract : XppObjectBase {
        
        private string caliberFieldField;
        
        private string gradeFieldField;
        
        private string itemDescriptionFieldField;
        
        private string itemNumberFieldField;
        
        private int numOfPalletsApprovedFieldField;
        
        private bool numOfPalletsApprovedFieldSpecified1Field;
        
        private int numOfPalletsFieldField;
        
        private bool numOfPalletsFieldSpecified1Field;
        
        private int numOfPalletsPostedFieldField;
        
        private bool numOfPalletsPostedFieldSpecified1Field;
        
        private string shadeFieldField;
        
        private decimal totalQtyFieldField;
        
        private bool totalQtyFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caliberField {
            get {
                return this.caliberFieldField;
            }
            set {
                this.caliberFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                this.gradeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemDescriptionField {
            get {
                return this.itemDescriptionFieldField;
            }
            set {
                this.itemDescriptionFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemNumberField {
            get {
                return this.itemNumberFieldField;
            }
            set {
                this.itemNumberFieldField = value;
            }
        }
        
        /// <remarks/>
        public int numOfPalletsApprovedField {
            get {
                return this.numOfPalletsApprovedFieldField;
            }
            set {
                this.numOfPalletsApprovedFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numOfPalletsApprovedFieldSpecified")]
        public bool numOfPalletsApprovedFieldSpecified1 {
            get {
                return this.numOfPalletsApprovedFieldSpecified1Field;
            }
            set {
                this.numOfPalletsApprovedFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int numOfPalletsField {
            get {
                return this.numOfPalletsFieldField;
            }
            set {
                this.numOfPalletsFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numOfPalletsFieldSpecified")]
        public bool numOfPalletsFieldSpecified1 {
            get {
                return this.numOfPalletsFieldSpecified1Field;
            }
            set {
                this.numOfPalletsFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public int numOfPalletsPostedField {
            get {
                return this.numOfPalletsPostedFieldField;
            }
            set {
                this.numOfPalletsPostedFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numOfPalletsPostedFieldSpecified")]
        public bool numOfPalletsPostedFieldSpecified1 {
            get {
                return this.numOfPalletsPostedFieldSpecified1Field;
            }
            set {
                this.numOfPalletsPostedFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shadeField {
            get {
                return this.shadeFieldField;
            }
            set {
                this.shadeFieldField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalQtyField {
            get {
                return this.totalQtyFieldField;
            }
            set {
                this.totalQtyFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("totalQtyFieldSpecified")]
        public bool totalQtyFieldSpecified1 {
            get {
                return this.totalQtyFieldSpecified1Field;
            }
            set {
                this.totalQtyFieldSpecified1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class DMExportOfflineContract : XppObjectBase {
        
        private decimal boxesOnPalletFieldField;
        
        private bool boxesOnPalletFieldSpecified1Field;
        
        private string caliberFieldField;
        
        private string deviceNameFieldField;
        
        private string deviceUserFieldField;
        
        private string gradeFieldField;
        
        private bool isApprovedByFGFieldField;
        
        private bool isApprovedByFGFieldSpecified1Field;
        
        private bool isApprovedBySLFieldField;
        
        private bool isApprovedBySLFieldSpecified1Field;
        
        private NoYes isOfflineModeFieldField;
        
        private bool isOfflineModeFieldSpecified1Field;
        
        private string palletNumFieldField;
        
        private string shadeFieldField;
        
        private string whLocationIdFieldField;
        
        /// <remarks/>
        public decimal boxesOnPalletField {
            get {
                return this.boxesOnPalletFieldField;
            }
            set {
                this.boxesOnPalletFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boxesOnPalletFieldSpecified")]
        public bool boxesOnPalletFieldSpecified1 {
            get {
                return this.boxesOnPalletFieldSpecified1Field;
            }
            set {
                this.boxesOnPalletFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string caliberField {
            get {
                return this.caliberFieldField;
            }
            set {
                this.caliberFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deviceNameField {
            get {
                return this.deviceNameFieldField;
            }
            set {
                this.deviceNameFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deviceUserField {
            get {
                return this.deviceUserFieldField;
            }
            set {
                this.deviceUserFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string gradeField {
            get {
                return this.gradeFieldField;
            }
            set {
                this.gradeFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool isApprovedByFGField {
            get {
                return this.isApprovedByFGFieldField;
            }
            set {
                this.isApprovedByFGFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isApprovedByFGFieldSpecified")]
        public bool isApprovedByFGFieldSpecified1 {
            get {
                return this.isApprovedByFGFieldSpecified1Field;
            }
            set {
                this.isApprovedByFGFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public bool isApprovedBySLField {
            get {
                return this.isApprovedBySLFieldField;
            }
            set {
                this.isApprovedBySLFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isApprovedBySLFieldSpecified")]
        public bool isApprovedBySLFieldSpecified1 {
            get {
                return this.isApprovedBySLFieldSpecified1Field;
            }
            set {
                this.isApprovedBySLFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        public NoYes isOfflineModeField {
            get {
                return this.isOfflineModeFieldField;
            }
            set {
                this.isOfflineModeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isOfflineModeFieldSpecified")]
        public bool isOfflineModeFieldSpecified1 {
            get {
                return this.isOfflineModeFieldSpecified1Field;
            }
            set {
                this.isOfflineModeFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string palletNumField {
            get {
                return this.palletNumFieldField;
            }
            set {
                this.palletNumFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shadeField {
            get {
                return this.shadeFieldField;
            }
            set {
                this.shadeFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whLocationIdField {
            get {
                return this.whLocationIdFieldField;
            }
            set {
                this.whLocationIdFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public enum NoYes {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Yes,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.DataManagerServices")]
    public partial class DMExportMiniContract : XppObjectBase {
        
        private string barCodePalletFieldField;
        
        private string dMShortDesc2FieldField;
        
        private string dMShortDescFieldField;
        
        private string palletNumFieldField;
        
        private long recordIdFieldField;
        
        private bool recordIdFieldSpecified1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string barCodePalletField {
            get {
                return this.barCodePalletFieldField;
            }
            set {
                this.barCodePalletFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dMShortDesc2Field {
            get {
                return this.dMShortDesc2FieldField;
            }
            set {
                this.dMShortDesc2FieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dMShortDescField {
            get {
                return this.dMShortDescFieldField;
            }
            set {
                this.dMShortDescFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string palletNumField {
            get {
                return this.palletNumFieldField;
            }
            set {
                this.palletNumFieldField = value;
            }
        }
        
        /// <remarks/>
        public long recordIdField {
            get {
                return this.recordIdFieldField;
            }
            set {
                this.recordIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recordIdFieldSpecified")]
        public bool recordIdFieldSpecified1 {
            get {
                return this.recordIdFieldSpecified1Field;
            }
            set {
                this.recordIdFieldSpecified1Field = value;
            }
        }
    }
}
